# Generated by Django 5.1.1 on 2024-10-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_alevel_result_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.ManyToManyField(related_name='teachers', to='accounts.subject'),
        ),
    ]
