# Generated by Django 5.1.1 on 2024-10-23 05:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_answer_image_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperupload',
            name='marking_scheme',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='marking_scheme'),
        ),
        migrations.AlterField(
            model_name='paperupload',
            name='paper',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='paper'),
        ),
    ]
