# Generated by Django 5.1.1 on 2024-10-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_paperupload_marking_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(choices=[('colombo', 'Colombo'), ('gampaha', 'Gampaha'), ('kandy', 'Kandy'), ('galle', 'Galle'), ('matara', 'Matara'), ('jaffna', 'Jaffna'), ('kaluthara', 'Kaluthara'), ('kurunegala', 'Kurunegala'), ('matale', 'Matale'), ('rathnapura', 'Rathnapura')], max_length=100),
        ),
    ]
