# Generated by Django 5.1.1 on 2024-11-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
